Repository bastionzero/zli, pull requests merged in 2021-11, with the labels that each got.

#249 Add ability for generate kubeConfig to append existing kubeconfig
  package.json
  src/handlers/generate-kube/generate-kube.command-builder.ts
  src/handlers/generate-kube/generate-kubeconfig.handler.ts
Labels: enhancement

#255 Fix zli disconnect on m1 cpus
  package.json
  src/services/kube/kube.service.ts
Labels: bug

#256 Update github template
  .github/pull_request_template.md
  package.json
Labels: documentation, refactor

#258 Ensure we await the call to kill the daemon
  package.json
  src/services/kube/kube.service.ts
Labels: bug

#248 System Tests
  .github/workflows/systemtest-ci.yml
  jest-config-unit-tests.js
  package-lock.json
  package.json
  src/cli-driver.ts
  src/handlers/attach/attach.handler.ts
  src/handlers/close-connection/close-connection.handler.ts
  src/handlers/connect/connect.handler.ts
  src/handlers/describe-cluster-policy/describe-cluster-policy.handler.ts
  src/handlers/generate-bash/generate-bash.command-builder.test.ts
  src/handlers/generate-bash/generate-bash.command-builder.ts
  src/handlers/generate-bash/generate-bash.handler.ts
  src/handlers/generate-kube/generate-kube-yaml.handler.ts
  src/handlers/group/fetch-groups.handler.ts
  src/handlers/list-connections/list-connections.handler.ts
  src/handlers/list-targets/list-targets.command-builder.ts
  src/handlers/list-targets/list-targets.handler.ts
  src/handlers/middleware.handler.ts
  src/handlers/policy/list-policies.handler.ts
  src/handlers/quickstart/quickstart-handler.ts
  src/handlers/ssh-proxy/ssh-proxy.handler.ts
  src/handlers/target-group/list-target-group.handler.ts
  src/handlers/target-user/list-target-users.handler.ts
  src/handlers/tunnel/status.handler.ts
  src/handlers/user/list-users.handler.ts
  src/services/config/config.service.ts
  src/services/http/http.service.ts
  src/services/list-targets/list-targets.service.ts
  src/services/logger/logger-config.service.ts
  src/services/oauth/oauth.service.ts
  src/services/quickstart/quickstart-ssm.service.ts
  src/services/ssm-target/ssm-target.service.ts
  src/system-tests/digital-ocean/digital-ocean-ssm-target-service.ts
  src/system-tests/digital-ocean/digital-ocean-ssm-target.service.types.ts
  src/system-tests/jest-config-system-tests.js
  src/system-tests/run-system-tests.sh
  src/system-tests/system-test-codebuild.yaml
  src/system-tests/tests/suites/connect.ts
  src/system-tests/tests/suites/list-targets.ts
  src/system-tests/tests/suites/version.ts
  src/system-tests/tests/system-test.ts
  src/system-tests/tests/utils.ts
  src/terminal/terminal.ts
  src/utils/shell-utils.ts
  src/utils/utils.test.ts
  src/utils/utils.ts
Labels: Feature Branch
