Repository bastionzero/zli, pull requests merged in 2021-12, with the labels that each got.

#263 Manually create cert/key for Daemon instead of using lib
  package-lock.json
  package.json
  src/handlers/generate-kube/generate-kubeconfig.handler.ts
  src/services/kube/kube.service.ts
Labels: bug

#262 Kube system test part 1: REST API plugin
  package-lock.json
  package.json
  src/handlers/tunnel/tunnel.handler.ts
  src/services/api-key/api-key.service.ts
  src/services/api-key/api-key.types.ts
  src/services/environment/environment.service.ts
  src/services/kube/kube.messages.ts
  src/services/kube/kube.service.ts
  src/services/policy/policy.service.ts
  src/system-tests/digital-ocean/digital-ocean-kube-service.ts
  src/system-tests/digital-ocean/digital-ocean-kube.service.types.ts
  src/system-tests/digital-ocean/digital-ocean-ssm-target-service.ts
  src/system-tests/digital-ocean/digital-ocean-ssm-target.service.types.ts
  src/system-tests/digital-ocean/digital-ocean.types.ts
  src/system-tests/system-test-codebuild.yaml
  src/system-tests/tests/suites/connect.ts
  src/system-tests/tests/suites/kube.ts
  src/system-tests/tests/suites/list-targets.ts
  src/system-tests/tests/suites/version.ts
  src/system-tests/tests/system-test.ts
  src/system-tests/tests/utils/helm/helm-utils.ts
  src/system-tests/tests/utils/helm/helm.types.ts
  src/system-tests/tests/utils/jest-utils.ts
  src/system-tests/tests/utils/utils.ts
  src/system-tests/tests/utils/zli-utils.ts
Labels: enhancement, tests

#266 Add check to see if port is still in use for kube daemon
  package-lock.json
  package.json
  src/handlers/tunnel/status.handler.ts
  src/services/kube/kube.service.ts
Labels: enhancement

#254 Bubble up daemon exit message to zli
  kube-go-assets/bctl/daemon/httpserver/httpserver.go
  package.json
  src/handlers/tunnel/status.handler.ts
  src/services/kube/kube.types.ts
Labels: enhancement

#272 Increase system test timeout for digital ocean droplet to become active
  package-lock.json
  package.json
  src/services/quickstart/quickstart-ssm.service.ts
  src/system-tests/digital-ocean/digital-ocean-ssm-target-service.ts
Labels: tests

#277 Catch case when kubeconfig does not exist
  package.json
  src/handlers/generate-kube/generate-kubeconfig.handler.ts
Labels: bug

#278 Ensure path var is send to exec in generate kubeConfig
  package.json
  src/handlers/generate-kube/generate-kubeconfig.handler.ts
Labels: bug
