Repository bastionzero/zli, pull requests merged in 2021-05, with the labels that each got.

#112 Handle non existent ssh proxy target [CWC-592]
  package.json
  src/handlers/middleware.handler.ts
  src/handlers/ssh-proxy.handler.ts
  src/logger.service/logger.ts
  src/oauth.service/oauth.service.ts
Labels: bug

#105 Attaching to existing open zli connections [CWC-667]
  package.json
  src/cli-driver.ts
  src/handlers/attach.handler.ts
  src/handlers/close-connection.handler.ts
  src/handlers/connect.handler.ts
  src/handlers/list-connections.handler.ts
  src/http.service/http.service.types.ts
  src/shell-utils.ts
  src/terminal/terminal.ts
  src/types.ts
  src/utils.ts
Labels: enhancement

#110 Force MFA setup as needed and some text fixes
  package.json
  src/cli-driver.ts
  src/handlers/login.handler.ts
  src/http.service/http.service.ts
  src/http.service/http.service.types.ts
Labels: bug, enhancement
