Repository bastionzero/zli, pull requests merged in 2022-11, with the labels that each got.

#572 [System Tests] Use beta agent for autodiscovery/ansible bzero targets
  .github/workflows/systemtest-ci-develop.yml
  .github/workflows/systemtest-ci-master.yml
  package-lock.json
  package.json
  src/http-services/auto-discovery-script/auto-discovery-script.http-services.ts
  src/system-tests/tests/system-test-setup.ts
Labels: Hotfix

#573 Apply #572 on develop
  .github/workflows/systemtest-ci-develop.yml
  .github/workflows/systemtest-ci-master.yml
  package-lock.json
  package.json
  src/http-services/auto-discovery-script/auto-discovery-script.http-services.ts
  src/system-tests/tests/suites/agent-recovery.ts
  src/system-tests/tests/system-test-setup.ts
Labels: enhancement

#580 Add list to quickstart policy tip
  package-lock.json
  package.json
  src/handlers/quickstart/quickstart-handler.ts
Labels: bug

#584 Send-logs should still work when daemon log file doesn't exist
  package.json
  src/handlers/send-logs/send-logs.handler.ts
  src/system-tests/tests/suites/send-logs.ts
Labels: bug

#585 Fix: Yet better daemon shutdown logic
  package-lock.json
  package.json
  src/handlers/connect/web-connect.handler.ts
  src/handlers/disconnect/disconnect.handler.ts
  src/handlers/logout/logout.handler.test.ts
  src/handlers/logout/logout.handler.ts
  src/services/daemon-management/daemon-management.service.test.ts
  src/services/daemon-management/daemon-management.service.ts
  src/services/daemon-management/types/disconnect-result.types.ts
  src/services/process-manager/process-manager.service.ts
  src/services/process-manager/process-manager.service.types.ts
  src/utils/daemon-utils.ts
Labels: bug

#590 Apply codebuild role to assume for service account ci to develop
  .github/workflows/systemtest-ci-master.yml
  package-lock.json
  package.json
Labels: bug, Hotfix
