Repository bastionzero/zli, pull requests merged in 2022-07, with the labels that each got.

#471 Skip delete agent pod test
  package.json
  src/system-tests/tests/suites/kube.ts
Labels: tests

#485 Reenable agent container autodiscovery tests
  package-lock.json
  package.json
  src/system-tests/tests/suites/agent-container.ts
Labels: bug, tests

#486 Isolate kube unit tests
  package.json
  src/handlers/generate/generate-kube-config.test.ts
Labels: bug, tests

#492 updating quickstart agent error message
  package.json
  src/services/quickstart/quickstart-ssm.service.ts
Labels: bug, documentation

#491 adding yum and apt install options to reference manual
  README.md
  package.json
Labels: documentation
