Repository bastionzero/zli, pull requests merged in 2022-10, with the labels that each got.

#545 System test updates for bzero bash autodiscovery script
  package-lock.json
  package.json
  src/http-services/auto-discovery-script/auto-discovery-script.http-services.ts
  src/system-tests/tests/suites/connect.ts
  src/system-tests/tests/system-test-setup.ts
  src/system-tests/tests/system-test.types.ts
  src/system-tests/tests/targets-to-run.ts
Labels: tests

#546 Always set zli me config in UserHttpService.Register
  package.json
  src/cli-driver.ts
  src/handlers/login/login.handler.ts
  src/http-services/user/user.http-services.ts
Labels: bug

#547 Ensure newline is added before setup commands added to bzero autodiscovery script
  package.json
  src/system-tests/tests/system-test-setup.ts
Labels: tests

#549 Fix shell terminal resize
  package.json
  src/utils/daemon-utils.ts
Labels: bug

#550 Use new bzero Ansible playbook in system tests
  package-lock.json
  package.json
  src/http-services/auto-discovery-script/auto-discovery-script.http-services.ts
  src/system-tests/digital-ocean/digital-ocean-ssm-target-service.ts
  src/system-tests/tests/suites/connect.ts
  src/system-tests/tests/system-test-setup.ts
  src/system-tests/tests/system-test.types.ts
  src/system-tests/tests/targets-to-run.ts
Labels: tests

#555 Convert quickstart from SSM agent to Bzero agent
  package-lock.json
  package.json
  src/handlers/quickstart/quickstart-handler.ts
  src/services/oauth/oauth.service.ts
  src/services/quickstart/quickstart.service.ts
  src/services/quickstart/quickstart.service.types.ts
Labels: enhancement, refactor

#562 Apply hotfix #561 on develop
  package-lock.json
  package.json
  src/services/http/http.service.ts
Labels: bug

#559 Create install script for ZLI that will work on MacOS and various Linux distros
  package-lock.json
  package.json
  scripts/install-zli.sh
Labels: enhancement

#563 Adjust user/register to not call user/me before mfaed [CWC-2174]
  package.json
  src/cli-driver.ts
  src/handlers/login/login.handler.ts
  src/http-services/user/user.http-services.ts
  src/services/oauth/oauth.service.ts
  src/system-tests/tests/system-test.ts
Labels: bug, Hotfix

#565 Adjust user/register to not call user/me before mfaed [CWC-2174]
  package.json
  src/cli-driver.ts
  src/handlers/login/login.handler.ts
  src/http-services/user/user.http-services.ts
  src/services/oauth/oauth.service.ts
  src/system-tests/tests/system-test.ts
Labels: bug, Hotfix

#571 [System Tests] Clear all timeouts started with sleepTimeout in afterAll
  package-lock.json
  package.json
  src/system-tests/tests/system-test.ts
  src/system-tests/tests/utils/test-utils.ts
Labels: bug
