Repository bastionzero/zli, pull requests merged in 2022-09, with the labels that each got.

#510 Improve SSH config file management
  package.json
  src/handlers/generate/generate-ssh-config.handler.ts
  src/handlers/generate/generate-ssh-config.mock.ts
  src/handlers/generate/generate-ssh-config.test.ts
  src/system-tests/tests/suites/ssh.ts
  src/system-tests/tests/utils/ssh-utils.ts
  src/utils/unit-test-utils.ts
Labels: documentation

#460 Bump eventsource from 1.1.0 to 1.1.1 and got from 11.8.2 to 11.8.5
  package-lock.json
  package.json
  src/system-tests/tests/suites/agent-recovery.ts
Labels: dependencies

#524 Update bzero snapshot images
  package-lock.json
  package.json
  src/system-tests/digital-ocean/digital-ocean-ssm-target.service.types.ts
  src/system-tests/tests/system-test-setup.ts
  src/system-tests/tests/system-test.ts
Labels: enhancement

#525 Update Al2 snapshot image with postgres configuration fix
  package.json
  src/system-tests/digital-ocean/digital-ocean-ssm-target.service.types.ts
Labels: bug, tests

#526 Fix al2 system tests
  package.json
  src/system-tests/digital-ocean/digital-ocean-ssm-target.service.types.ts
Labels: bug, tests

#528 Fix typo in bzero-bz-config file generation
  package.json
  src/handlers/generate/generate-ssh-config.handler.ts
  src/handlers/generate/generate-ssh-config.mock.ts
Labels: bug, documentation

#521 Add default target user for shell and ssh connections
  package.json
  src/cli-driver.ts
  src/handlers/configure/config-default-targetuser.command-builder.ts
  src/handlers/configure/config-default-targetuser.handler.ts
  src/handlers/configure/config.handler.ts
  src/handlers/connect/connect.handler.test.ts
  src/handlers/connect/connect.handler.ts
  src/handlers/generate/generate-ssh-config.handler.ts
  src/handlers/generate/generate-ssh-config.mock.ts
  src/handlers/generate/generate-ssh-config.test.ts
  src/services/config/config.service.ts
  src/services/config/config.service.types.ts
Labels: Feature Branch

#536 Clear ssh keypath before running system test
  package.json
  src/services/config/config.service.ts
  src/system-tests/tests/suites/ssh.ts
  src/system-tests/tests/system-test.ts
Labels: bug

#541 Tab Completion
  package-lock.json
  package.json
  src/cli-driver.ts
  src/handlers/close-connection/close-connection.command-builder.ts
  src/handlers/configure/config-default-targetuser.command-builder.ts
  src/handlers/connect/connect.command-builder.ts
  src/handlers/default-target-group/default-target-group.command-builder.ts
  src/handlers/generate/generate-kube.command-builder.ts
  src/handlers/generate/generate-ssh-config.command-builder.ts
  src/handlers/list-connections/list-connections.command-builder.ts
  src/handlers/list-daemons/list-daemons.command-builder.ts
  src/handlers/list-targets/list-targets.command-builder.ts
  src/handlers/middleware.handler.ts
  src/handlers/policy/policy-group/list-groups.command-builder.ts
  src/handlers/policy/policy-list/policy-list.command-builder.ts
  src/handlers/policy/policy-targetgroup/list-targetgroups.command-builder.ts
  src/handlers/policy/policy-targetuser/list-targetusers.command-builder.ts
  src/handlers/policy/policy-user/list-users.command-builder.ts
  src/utils/utils.ts
Labels: Feature Branch
