Repository bastionzero/zli, pull requests merged in 2022-04, with the labels that each got.

#353 Update github template to include related to hotfix section
  .github/pull_request_template.md
  package.json
Labels: enhancement

#358 Ensure we send n/a for args incase there are no args passed
  package.json
  src/services/Tracking/google-analytics.service.ts
Labels: bug

#355 Fixed filtering bug [CWC-1664]
  package.json
  src/utils/utils.ts
Labels: bug

#350 Fix version check warning
  package-lock.json
  package.json
  src/middlewares/check-version-middleware.ts
Labels: bug

#370 Ensure that list-targets table is correctly formatted
  package.json
  src/utils/utils.ts
Labels: bug

#377 Update async dependency
  package-lock.json
  package.json
Labels: dependencies

#378 Hotfix: broken ssh proxy hostname
  package.json
  src/handlers/generate-config/generate-ssh-config.handler.ts
  src/handlers/ssh-proxy-config.handler.ts
Labels: Hotfix

#396 Add groups based tests
  package.json
  src/http-services/organization/organization.http-services.ts
  src/system-tests/run-system-tests.sh
  src/system-tests/tests/suites/groups.ts
  src/system-tests/tests/suites/rest-api/organization.ts
  src/system-tests/tests/system-test.ts
  src/system-tests/tests/system-test.types.ts
  src/system-tests/tests/targets-to-run.ts
  src/system-tests/tests/utils/utils.ts
Labels: tests

#394 Add Iperf Tests Suite
  Codebuild/system-test-codebuild.yaml
  package.json
  src/system-tests/tests/suites/iperf.ts
  src/system-tests/tests/suites/vt.ts
  src/system-tests/tests/system-test-setup.ts
  src/system-tests/tests/system-test.ts
  src/system-tests/tests/utils/test-utils.ts
  src/utils/daemon-utils.ts
Labels: tests

#403 Fix/ssm attach
  package-lock.json
  package.json
  src/handlers/attach/attach.handler.ts
Labels: bug

#402 Fix IN_CI comparison
  package.json
  src/system-tests/tests/system-test.ts
Labels: bug

#405 Fix env var name for runner creation
  package.json
  src/http-services/organization/organization.http-services.ts
  src/system-tests/tests/suites/kube.ts
  src/system-tests/tests/suites/vt.ts
  src/system-tests/tests/system-test.ts
  src/system-tests/tests/targets-to-run.ts
Labels: bug

#404 Fix/ssm attach - develop
  package-lock.json
  package.json
  src/handlers/attach/attach.handler.ts
Labels: bug, Hotfix

#387 Add zli close unit tests + system test
  package.json
  src/handlers/close-connection/close-connection.handler.test.ts
  src/system-tests/tests/suites/connect.ts
  src/system-tests/tests/suites/kube.ts
  src/system-tests/tests/suites/rest-api/policies/policies.ts
  src/system-tests/tests/system-test.types.ts
  src/system-tests/tests/targets-to-run.ts
  src/system-tests/tests/utils/utils.ts
  src/utils/unit-test-utils.ts
Labels: tests

#408 Fixup bad console.log
  package.json
  src/system-tests/tests/suites/rest-api/organization.ts
  src/system-tests/tests/system-test.ts
  src/system-tests/tests/targets-to-run.ts
Labels: bug, tests

#386 Session recording test suite
  src/http-services/session-recording/session-recording.http-services.ts
  src/services/http/http.service.ts
  src/system-tests/tests/suites/session-recording.ts
  src/system-tests/tests/system-test.ts
  src/system-tests/tests/system-test.types.ts
  src/system-tests/tests/targets-to-run.ts
  src/system-tests/tests/utils/utils.ts
Labels: tests

#412 Fix dynamic local port selection for db+web targets
  package-lock.json
  package.json
  src/handlers/connect/db-connect.handler.ts
  src/handlers/connect/web-connect.handler.ts
  src/handlers/disconnect/disconnect.handler.ts
  src/handlers/logout.handler.ts
  src/utils/daemon-utils.ts
Labels: bug, Hotfix
