Repository bastionzero/zli, pull requests merged in 2022-06, with the labels that each got.

#441 Add Support for Container Agents
  package-lock.json
  package.json
  src/system-tests/digital-ocean/digital-ocean-ssm-target-service.ts
  src/system-tests/tests/suites/agent-container.ts
  src/system-tests/tests/suites/dynamic-access.ts
  src/system-tests/tests/system-test-setup.ts
  src/system-tests/tests/system-test.ts
  src/system-tests/tests/targets-to-run.ts
  src/system-tests/tests/utils/AgentContainerDockerfiles/al2.Dockerfile
  src/system-tests/tests/utils/AgentContainerDockerfiles/entrypoint.sh
  src/system-tests/tests/utils/AgentContainerDockerfiles/ubuntu.Dockerfile
  src/system-tests/tests/utils/connect-utils.ts
Labels: enhancement

#462 System tests: Add support for cleaning up agent container pods
  package-lock.json
  package.json
  src/system-tests/tests/suites/agent-container.ts
Labels: enhancement

#467 Direct proxy policy update to the correct endpoint [CWC-1939]
  package.json
  src/http-services/policy/policy.http-services.ts
Labels: bug, Hotfix

#468 Direct proxy policy update to the correct endpoint [CWC-1939]
  package.json
  src/http-services/policy/policy.http-services.ts
Labels: bug, Hotfix

#474 Use npm v8 in webshell-cli-release codebuild spec
  webshell-cli-release.yml
Labels: bug
