Repository bastionzero/zli, pull requests merged in 2022-01, with the labels that each got.

#274 Add self registration flow in system tests
  package-lock.json
  package.json
  src/system-tests/digital-ocean/digital-ocean-ssm-target-service.ts
  src/system-tests/digital-ocean/digital-ocean-ssm-target.service.types.ts
  src/system-tests/tests/suites/connect.ts
  src/system-tests/tests/system-test.ts
  src/system-tests/tests/system-test.types.ts
Labels: tests

#281 Okta login ports [CWC-1403]
  package.json
  src/services/oauth/oauth.service.ts
Labels: refactor

#285 Fix target disambiguate
  package.json
  src/cli-driver.ts
  src/utils/utils.test.ts
  src/utils/utils.ts
Labels: bug
