Repository bastionzero/zli, pull requests merged in 2023-05, with the labels that each got.

#674 Await set mrTap config [CWC-2567]
  package.json
  src/services/config/config.service.ts
Labels: enhancement

#676 Silently fail when grabbing manifest
  package-lock.json
  package.json
  src/middlewares/check-version-middleware.ts
Labels: bug

#675 Rename windows zli executable
  Codebuild/check-pr.yml
  Codebuild/system-test-codebuild.yaml
  Codebuild/unit-test.yml
  Codebuild/zli-release.yml
  package-lock.json
  package.json
  src/middlewares/check-version-middleware.ts
Labels: enhancement

#673 MFA Grace Period Integration and UX Improvements
  package-lock.json
  package.json
  src/handlers/login/login.handler.ts
  src/services/oauth/oauth.service.ts
  src/services/oauth/templates/login.ts
  src/system-tests/tests/suites/rest-api/mfa.ts
Labels: enhancement

#678 Create lock in config folder
  package-lock.json
  package.json
  src/utils/daemon-utils.ts
Labels: bug, Hotfix

#679 Apply #678 hotfix to develop
  package-lock.json
  package.json
  src/utils/daemon-utils.ts
Labels: Hotfix

#680 Refresh lock
  package-lock.json
  package.json
  src/handlers/quickstart/quickstart-handler.ts
  src/services/oauth/oauth.service.ts
Labels: enhancement, ci-run-serviceaccount, ci-run-google

#684 Release 5-5-2023
  package-lock.json
  package.json
  src/handlers/quickstart/quickstart-handler.ts
  src/services/oauth/oauth.service.ts
Labels: release

#686 Add Windows Installation Instructions
  README.md
  package-lock.json
  package.json
Labels: documentation

#688 Windows unit tests
  package-lock.json
  package.json
  src/handlers/generate/kube/generate-kube-config.test.ts
  src/handlers/generate/ssh/generate-ssh-config.mock.ts
  src/handlers/generate/ssh/generate-ssh-proxy.mock.ts
  src/handlers/generate/ssh/generate-ssh-proxy.test.ts
  src/services/kube-management/kube-management.service.test.ts
  src/services/kube-management/kube-management.service.ts
Labels: refactor

#690 Unhide splitcert commands
  package-lock.json
  package.json
  src/cli-driver.ts
  src/handlers/policy/policy-create/create-policy.command-builder.ts
Labels: documentation

#696 OPA Microservice System Test Changes
  package-lock.json
  package.json
  src/system-tests/tests/suites/agent-container.ts
  src/system-tests/tests/suites/agent-recovery.ts
  src/system-tests/tests/suites/connect.ts
  src/system-tests/tests/suites/db.ts
  src/system-tests/tests/suites/dynamic-access.ts
  src/system-tests/tests/suites/force-register.ts
  src/system-tests/tests/suites/groups.ts
  src/system-tests/tests/suites/iperf.ts
  src/system-tests/tests/suites/kube.ts
  src/system-tests/tests/suites/rest-api/mfa.ts
  src/system-tests/tests/suites/service-account.ts
  src/system-tests/tests/suites/session-recording.ts
  src/system-tests/tests/suites/ssh.ts
  src/system-tests/tests/suites/web.ts
  src/system-tests/tests/system-test.ts
Labels: tests

#698 Exit on zli with no commands
  package-lock.json
  package.json
  src/cli-driver.ts
Labels: bug
