Repository bastionzero/zli, pull requests merged in 2023-03, with the labels that each got.

#639 Fix kube system tests to work against v2 of the helm chart
  package-lock.json
  package.json
  src/system-tests/tests/suites/kube.ts
Labels: tests

#640 Use target id if available else use target name for logging in `zli send-logs`
  package.json
  src/handlers/send-logs/send-logs.handler.ts
Labels: bug

#642 Adjust zli development instructions in README [CWC-2487]
  README.md
  package.json
Labels: enhancement

#645 Fix zli dependencies instructions [CWC-2487]
  .gitmodules
  README.md
  package.json
Labels: documentation

#648 Apply 647 on develop
  package-lock.json
  package.json
  src/system-tests/tests/utils/connect-utils.ts
Labels: tests

#643 Fix race condition when provisioning multiple daemons
  package-lock.json
  package.json
  src/utils/daemon-exit-codes.ts
  src/utils/daemon-utils.ts
Labels: bug

#649 Support 1:1 IdP usernames as target user in system tests
  package.json
  src/handlers/list-targets/list-targets.test.ts
  src/system-tests/tests/suites/agent-recovery.ts
  src/system-tests/tests/suites/connect.ts
  src/system-tests/tests/suites/groups.ts
  src/system-tests/tests/suites/rest-api/policies/policies-target-connect.ts
  src/system-tests/tests/suites/service-account.ts
  src/system-tests/tests/suites/session-recording.ts
  src/system-tests/tests/suites/ssh.ts
  src/system-tests/tests/system-test-setup.ts
  src/system-tests/tests/system-test.types.ts
  src/system-tests/tests/targets-to-run.ts
  src/system-tests/tests/utils/connect-utils.ts
Labels: Feature Branch, ci-run-serviceaccount, ci-run-google

#654 Temp fix for github clone issues inside AWS codebuild docker containers
  Codebuild/check-pr.yml
  Codebuild/system-test-codebuild.yaml
  Codebuild/unit-test.yml
  package-lock.json
  package.json
Labels: bug, tests

#655 Release 03/29/23
  Codebuild/check-pr.yml
  Codebuild/system-test-codebuild.yaml
  Codebuild/unit-test.yml
  package-lock.json
  package.json
Labels: release
