Repository bastionzero/zli, pull requests merged in 2023-02, with the labels that each got.

#629 Update systems tests to work with helm v2
  package-lock.json
  package.json
  src/system-tests/digital-ocean/digital-ocean-kube-service.ts
  src/system-tests/tests/suites/kube.ts
  src/system-tests/tests/system-test-setup.ts
  src/system-tests/tests/system-test.ts
Labels: enhancement

#631 Fix policy creation bugs and logger bugs
  package-lock.json
  package.json
  src/handlers/login/login.handler.ts
  src/handlers/policy/policy-create/create-cluster-policy.handler.ts
  src/handlers/policy/policy-create/create-proxy-policy.handler.ts
  src/handlers/policy/policy-create/create-recording-policy.handler.ts
  src/handlers/policy/policy-create/create-tconnect-policy.handler.ts
  src/handlers/service-account/configure-service-account.handler.ts
  src/middlewares/oauth-middleware.ts
Labels: Hotfix

#633 Apply policy hotfix back to develop
  package-lock.json
  package.json
  src/handlers/login/login.handler.ts
  src/handlers/policy/policy-create/create-cluster-policy.handler.ts
  src/handlers/policy/policy-create/create-proxy-policy.handler.ts
  src/handlers/policy/policy-create/create-recording-policy.handler.ts
  src/handlers/policy/policy-create/create-tconnect-policy.handler.ts
  src/handlers/service-account/configure-service-account.handler.ts
  src/middlewares/oauth-middleware.ts
Labels: bug

#636 Zli manual reminder [CWC-2463]
  .github/pull_request_template.md
  package.json
Labels: enhancement
